/* translations/es.js — Español */
window.MINDTEST_TRANS = {
  ui: {
    'site.brand':'MindTest','site.brand.mid':'Mind','site.brand.dot':'Test',
    'site.tagline':'Tests de psicología en 3 minutos','site.lede':'Sin registro. Sin instalación. Comparte resultados al instante.',
    'site.footer':'Tests de psicología divertidos','site.sister':'Sitio hermano',
    'btn.copy':'🔗 Copiar enlace','btn.tweet':'𝕏 Compartir','btn.other':'🎲 Ver otros tests',
    'btn.retry':'↻ Repetir test','toast.copied':'¡Enlace copiado!',
    'share.hint':'Pega el enlace copiado en WhatsApp o Instagram para mostrar la tarjeta de resultados.',
    'home.h1':'Elige un test',
    'result.traits':'Tus características','result.tip':'Un consejo','result.match':'Tipo más compatible','result.desc':'¿Qué tipo eres?',
    'kicker.love':'Resultado: Estilo de amor','kicker.kkondae':'Resultado: Test Anticuado','kicker.vocab':'Resultado: Vocabulario coreano',
    'kicker.burnout':'Resultado: Diagnóstico de agotamiento','kicker.digital':'Resultado: Dependencia digital','kicker.tmi':'Resultado: Tipo TMI',
    'badge.burnout':'Nivel de agotamiento: {v}%','badge.digital':'Dependencia digital: {v}%','badge.kkondae':'Índice anticuado: {v}%',
    'card.love.title':'Test de estilo de amor','card.love.desc':'12 preguntas para descubrir cuál de los 16 tipos de amor eres tú.','card.love.meta':'12 preguntas · 16 tipos',
    'card.kkondae.title':'Test anticuado','card.kkondae.desc':'¿Eres de mente abierta o secretamente chapado a la antigua? 10 preguntas.','card.kkondae.meta':'10 preguntas · 5 niveles',
    'card.vocab.title':'Test de vocabulario coreano','card.vocab.desc':'¿Puedes entender las expresiones coreanas más confusas? Ponlo a prueba.','card.vocab.meta':'10 preguntas · 6 niveles',
    'card.burnout.title':'Diagnóstico de agotamiento','card.burnout.desc':'Alarma del lunes, vacío después del trabajo... Mide tu nivel de burnout ahora.','card.burnout.meta':'10 preguntas · 5 niveles',
    'card.digital.title':'Test de dependencia digital','card.digital.desc':'Móvil al despertar, durante la comida, antes de dormir. Mide tu dependencia.','card.digital.meta':'10 preguntas · 5 niveles',
    'card.tmi.title':'Test de tipo TMI','card.tmi.desc':'Profundidad, timing, reacción: 3 ejes que revelan tu estilo de conversación.','card.tmi.meta':'9 preguntas · 8 tipos'
  },
  tests: {
    love: {
      title:'Test de estilo de amor', subtitle:'12 preguntas · 16 tipos', shareText:'¡Acabo de hacer el test de estilo de amor! ¡Pruébalo tú también!',
      questions:[
        {q:'Tu crush lleva 6 horas sin responder. Tú:',a:['Escribo primero. No puedo evitarlo.','Compruebo si está en línea y espero. No quiero parecer desesperado/a.']},
        {q:'Siguen mandando señales de que les gustas.',a:['Lo digo directamente: "¿Te gusto?"','Espero hasta estar completamente seguro/a.']},
        {q:'Acabas de llegar a casa después de una cita increíble.',a:['"Esta noche ha sido increíble" — enviado al instante.','Ser el primero en escribir se siente como perder. Solo mando "Buenas noches."']},
        {q:'Primera cita con muy buena química.',a:['Quedamos para la próxima cita ahí mismo.','Necesito verla unas veces más para estar seguro/a.']},
        {q:'Dos semanas de relación.',a:['Ya estoy planeando mentalmente el día 100.','Aún nos estamos conociendo. Sin prisas.']},
        {q:'Si tu relación tuviera un gráfico de temperatura:',a:['Más caliente al principio. Intensidad máxima desde el día uno.','Necesita unos 3 meses para calentarse de verdad.']},
        {q:'Un fin de semana libre con tu pareja.',a:['Juntos los dos días, obviamente.','Un día separados, un día juntos. El equilibrio perfecto.']},
        {q:'Tu pareja se va de viaje con amigos.',a:['"¿Puedo ir yo también?" es mi primera reacción.','¡Que lo pasen bien! Y planeo mi propio fin de semana.']},
        {q:'¿Con qué frecuencia os escribís al día?',a:['Actualizaciones en directo. Lo que comí, todo.','Por la mañana y por la noche es suficiente.']},
        {q:'Regalo de aniversario:',a:['Carta manuscrita + sorpresa. La emoción lo es todo.','Exactamente lo que dijeron que querían. Práctico = amoroso.']},
        {q:'Si te preguntan "¿Por qué estamos juntos?":',a:['Quiero decir "porque era el destino."','"Porque estamos cómodos juntos" — esa es la respuesta honesta.']},
        {q:'¿Qué importa más en el amor?',a:['Las mariposas. Sin emoción = sin amor.','La estabilidad. No pelearse y durar mucho.']}
      ],
      results:{
        'romance-express':{name:'Tren desbocado del romance',emoji:'🚂',summary:'Sin frenos. A toda velocidad en cuanto llegan los sentimientos.',desc:'Cuando los sentimientos llegan, no hay manera de esconderlos. Escribes primero, confiesas primero, y ya tienes planes para el aniversario. Estar contigo hace que cualquiera se sienta amado todo el día. Solo asegúrate de que puedan seguir tu ritmo.',traits:['Del enamoramiento a la confesión en tiempo récord','Memorizas los aniversarios antes que ellos','Un largo silencio te arruina todo el día','"¿No estamos destinados el uno para el otro?" — y lo dices en serio'],tip:'A veces intenta adaptarte a su ritmo. Esperar también es parte del amor.',match:'Tienda 24 horas'},
        'always-open':{name:'Tienda 24 horas',emoji:'🏪',summary:'Siempre abierto, siempre ahí para ti.',desc:'Rápido para expresarse, le encanta estar cerca, pero mantiene los pies en el suelo. Cuando alguien está enfermo, llevas medicina en lugar de palabras dulces. Estar contigo significa nunca sentirse solo.',traits:['Responde incluso a las 3 de la madrugada','El regalo = exactamente lo que pidieron','Las acciones van antes que las palabras','Los conflictos se resuelven el mismo día'],tip:'Hacer todo te agota. Aprende a recibir también.',match:'Tren desbocado del romance'},
        'firework-confessor':{name:'Fuegos artificiales',emoji:'🎆',summary:'Gran explosión, luego de vuelta a tu espacio.',desc:'Grande y atrevido/a al expresar sentimientos, pero no necesita estar juntos las 24h. Amar con intensidad, vivir por separado. La pareja se sorprende al principio, luego se alivia.',traits:['Las confesiones son de nivel espectacular','Poco contacto pero 100% presente en persona','Necesita tiempo a solas para seguir amando bien','Cero dependencia'],tip:'Las diferencias de temperatura confunden. Manda una señal durante los momentos tranquilos.',match:'Hada ansiosa'},
        'instant-deal':{name:'Cierre rápido',emoji:'📄',summary:'No soporta la ambigüedad. Lo decide rápido.',desc:'Sentimientos claros = palabras claras, y finales claros también. El despilfarro emocional es un desperdicio. Estableces expectativas pronto, así que las relaciones empiezan de forma limpia.',traits:['El primero en preguntar "¿Qué somos?"','El itinerario de la cita incluye el tiempo de transporte','Quiere soluciones, no espirales emocionales','El amor es una actividad planificada'],tip:'La eficiencia está bien, pero algunos sentimientos necesitan ser escuchados sin solución.',match:'Soñador de bodas'},
        'slow-clinger':{name:'Lento y pegajoso',emoji:'🍡',summary:'Lento para empezar, difícil de soltar.',desc:'Se expresa libremente pero sin prisa. Una vez que dejas entrar a alguien, te quedas cerca. Sin grandes gestos — mensajes constantes a la misma hora cada día son tu lenguaje del amor.',traits:['Tarda en confesar, pero va a la distancia una vez que lo hace','El tiempo juntos lo es todo','Nunca olvida un pequeño aniversario','Prefiere las rutinas a la novedad'],tip:'Demasiada familiaridad = la pareja lo da por sentado. Prueba un nuevo lugar de cita de vez en cuando.',match:'El Estratega'},
        'caring-butler':{name:'El mayordomo devoto',emoji:'🧺',summary:'Lenguaje del amor: cuidar de todo en silencio.',desc:'Recuerdas alergias, fechas de exámenes, preferencias. La vida simplemente se vuelve más organizada a tu alrededor.',traits:['Sabe su lista de alergias y horario de exámenes','Sincroniza rutinas desde el primer día','No deja que las cosas escalen','"¿Estás bien?" siempre está en tus labios'],tip:'Cuidar como hábito = perder tu propia ventana emocional. Di lo que duele, cuando duele.',match:'Llama silenciosa'},
        'letter-romantic':{name:'El escritor de cartas',emoji:'💌',summary:'Registra cada momento del amor.',desc:'Corazón amplio pero ritmo pausado en la relación. Pocas citas, pero cada una está diseñada. Fotos, cartas, playlists — archivas el amor.',traits:['Cartas manuscritas para los aniversarios','Diseña de antemano el ambiente de cada cita','Respeta el espacio pero no esconde el anhelo','Recuerda el amor como una historia'],tip:'Obsesionarse con los momentos perfectos hace que los ordinarios parezcan fracasos. Ama también los días aburridos.',match:'Realista directo'},
        'honest-realist':{name:'Realista directo',emoji:'🥗',summary:'Limpio, directo, sin juegos.',desc:'Lo dice cuando es bueno, sin jalar y empujar artificiales. No hay prisa ni dependencia. Respeta la vida de cada uno y construye algo duradero.',traits:['Nunca tuerce los sentimientos para decir otra cosa','La vida no se derrumba por el amor','Establece expectativas pronto','Casi sin rencores'],tip:'Demasiado discreto y pensarán que no te importa. Una frase cursi de vez en cuando hace magia.',match:'El escritor de cartas'},
        'quiet-flame':{name:'Llama silenciosa',emoji:'🔥',summary:'Frío por fuera, ardiendo por dentro.',desc:'Los sentimientos se encienden rápido pero la expresión va con retraso. Quieres estar cerca e imaginar todo, pero mantienes cara de póker. Obtienes la reacción "¿Espera, te gustaba yo?"',traits:['Ya has jugado varios escenarios en tu cabeza','Has visto silenciosamente todas sus publicaciones','30 minutos de debate antes de escribir primero','Indiferente al principio, azorado cuando te pillan'],tip:'Los sentimientos no expresados no llegan. Una frase es suficiente.',match:'El mayordomo devoto'},
        'secret-santa':{name:'Papá Noel secreto',emoji:'🎁',summary:'Nunca lo anuncia, pero ya está hecho.',desc:'Los sentimientos llegan rápido y quieres estar cerca, pero te expresas con acciones, no con palabras. Trajiste un paraguas extra porque sabías que no tenían uno.',traits:['Se expresa con acciones, no con palabras','Nunca se lleva el mérito','Detecta lo que se necesita antes de que se diga','Ya actúa como pareja antes de la confesión'],tip:'Esperar a que te noten tarda demasiado. Expresarse no es presumir.',match:'Maestro del juego'},
        'push-pull-master':{name:'Maestro del juego',emoji:'🎣',summary:'El corazón ya corre, las manos van despacio.',desc:'Se enamora rápido pero nunca lo muestra primero. Mantiene una distancia cómoda, solo aparece en los momentos románticos. Ellos sienten curiosidad sin parar. Magnético, pero agotador a largo plazo.',traits:['Lee el mensaje, responde 10 minutos después — a propósito','Actúa en el momento decisivo','Casi nunca dijo "me gustas" primero','Fingir no importarle es tu habilidad'],tip:'El juego solo funciona al principio. La honestidad pega más fuerte una vez establecido.',match:'Papá Noel secreto'},
        'tactician':{name:'El Estratega',emoji:'🎯',summary:'Lee la situación antes que el corazón.',desc:'Los sentimientos llegan rápido pero la expresión es controlada. Protege el espacio individual, verifica la compatibilidad real. Menos movimientos imprudentes = menos fracasos. Pero tardas mucho en empezar.',traits:['Calcula el momento de la confesión','Línea clara entre amor y vida cotidiana','Lee la situación antes que los sentimientos','Corta limpio cuando no es lo correcto'],tip:'Calcular demasiado deja pasar a buenas personas. Arriésgate a veces.',match:'Lento y pegajoso'},
        'anxious-fairy':{name:'Hada ansiosa',emoji:'📱',summary:'No puede decirlo, pero necesita estar cerca.',desc:'Imagina todo cuando las respuestas se detienen pero no puede preguntar "¿Por qué no respondes?" Traga el dolor y lo saca mucho después. Amor profundo, pero muchas horas sufriendo sola.',traits:['Revisa el chat múltiples veces cuando hay un no leído','No puede decir lo que duele de inmediato','Detecta cambios de tono al instante','Infinitamente cálido una vez tranquilizado'],tip:'La ansiedad se resuelve en 5 segundos de preguntar. Verificar no es posesivo.',match:'Fuegos artificiales'},
        'tsundere-master':{name:'El Tsundere',emoji:'😾',summary:'La boca dice no, las acciones dicen sí.',desc:'Mostrar afecto es lo más incómodo del mundo. Dice "da igual" pero cuida de todo de todas formas. Una vez que la pareja aprende a decodificarte, el vínculo se vuelve indestructible.',traits:['Desvía los cumplidos','Traduce la preocupación en regaños','El asiento de al lado siempre está vacío — para ellos','Sin expresión, pero recuerda todo'],tip:'No dejes todo el descifrado a ellos. Ve directo unas pocas veces al año.',match:'Soñador de bodas'},
        'daydream-wedding':{name:'Soñador de bodas',emoji:'💒',summary:'Cero progreso real, progreso mental infinito.',desc:'Expresión lenta, ritmo lento, mantiene distancia — pero ya ha planeado un futuro juntos en detalle. Océano de romance por dentro, apenas una gota sale. Esa brecha es tu encanto y tu desafío.',traits:['Planea el futuro antes de salir oficialmente','Esperando que confiesenmi primero','Los sentimientos se vuelven más fuertes cuando está solo','Mantiene a una persona en mente durante mucho tiempo'],tip:'La imaginación no hace avanzar las relaciones. Da un paso real hoy.',match:'Cierre rápido'},
        'careful-fossil':{name:'El fósil cuidadoso',emoji:'🗿',summary:'Solo confía en lo que ha sido verificado.',desc:'Todo es cauteloso: expresión, ritmo, distancia, realidad. Empieza muy lentamente. Pero una vez comprometido, casi nada lo sacude. La certeza cuesta tiempo — y esa es la única forma de conseguirla.',traits:['No empieza sin certeza','La rutina de vida no cambia por amor','Confía en la consistencia sobre los eventos','Va la distancia una vez que se da el corazón'],tip:'Esperar a que todo esté confirmado significa que el momento ya pasó. Da un paso.',match:'Tren desbocado del romance'}
      }
    },
    kkondae:{
      title:'Test anticuado',subtitle:'10 preguntas · 5 niveles',shareText:'Acabo de medir mi índice anticuado. ¡Pruébalo tú también!',
      questions:[
        {q:'Un compañero más joven no está de acuerdo contigo en el trabajo.',a:['Bien que hable — las perspectivas frescas son valiosas.','Debería aprender lo básico antes de cuestionar a los mayores.','Si el tono es correcto, está bien.']},
        {q:'Estás enseñando a alguien cómo hacer una tarea.',a:['Explico una vez y le dejo que lo resuelva.','Que mire cómo lo hago yo y lo copie.','Explico paso a paso y verifico la comprensión.']},
        {q:'Un empleado joven reserva un restaurante sin preguntarte.',a:['Buena iniciativa. Aprecio la proactividad.','Debería haber preguntado primero. Los mayores eligen el lugar.','Depende del contexto; la iniciativa a veces es buena.']},
        {q:'Ves a un joven aburrido durante tus consejos.',a:['Quizás mi consejo no llega — lo ajustaré.','Son desagradecidos. La experiencia vital no tiene precio.','Haré una pausa y comprobaré si necesitan algo diferente.']},
        {q:'Alguien más joven gana más que tú.',a:['Justo — las habilidades y resultados importan más que la edad.','Algo está mal en el sistema.','Sentimientos encontrados, pero respeto su logro.']},
        {q:'Escuchas un slang que no entiendes.',a:['Pregunto qué significa — curioso/a por el nuevo lenguaje.','Los jóvenes de hoy... incomprensibles.','Lo busco en Google después.']},
        {q:'Tu infancia fue más dura que la juventud de hoy.',a:['Cada era tiene sus propias dificultades.','Los jóvenes de hoy lo tienen demasiado fácil.','Desafíos diferentes, no necesariamente más fácil.']},
        {q:'Estabas equivocado en una discusión con un subordinado.',a:['Lo reconozco claramente — estar equivocado no da vergüenza.','Quedarme callado es como reconocerlo.','Lo reconozco indirectamente para guardar las apariencias.']},
        {q:'Un joven te enseña algo nuevo.',a:['Me encanta — todo el mundo puede aprender de cualquiera.','Incómodo — se siente como si estuviera presumiendo.','Agradecido, pero un poco incómodo.']},
        {q:'¿Qué significa "respetar a los mayores" para ti?',a:['El respeto lo da el carácter, no la edad.','La antigüedad merece automáticamente deferencia.','La edad gana respeto básico, el carácter gana más.']}
      ],
      grades:[
        {name:'Agua pura',emoji:'💧',summary:'Índice anticuado cero. Genuinamente abierto.',desc:'Sin rastro de pensamiento anticuado. Ves a todas las personas como iguales, escuchas con curiosidad y actualizas tus puntos de vista fácilmente. Raro y refrescante.',traits:['La edad no significa nada en tu evaluación','Te encanta aprender de los jóvenes','Admites errores sin vacilar','Juzgas las ideas, no la antigüedad'],tip:'Tu apertura es una superpotencia. Mantenla.'},
        {name:'Brote',emoji:'🌱',summary:'Sobre todo abierto — con algún momento anticuado.',desc:'Mayoritariamente flexible, pero ocasionalmente aparece el "en mis tiempos". Impulsado principalmente por el mérito y la apertura.',traits:['Normalmente basado en el mérito','Frustración ocasional con la actitud de los jóvenes','Mayoritariamente dispuesto a aprender','Momentos de jerarquía raros'],tip:'Nota cuando se cuela el pensamiento basado en la edad y cuestionarlo.'},
        {name:'Cincuenta y cincuenta',emoji:'⚖️',summary:'Mitad abierto, mitad tradicional.',desc:'Genuinamente dividido entre lo antiguo y lo nuevo. A veces flexible, a veces jerárquico. Suele adaptarse al contexto — pero la mezcla puede confundir a la gente.',traits:['Abierto en unas situaciones, tradicional en otras','Sentimientos encontrados sobre las brechas salariales por edad','Se ajusta con el contexto','Reglas inconsistentes'],tip:'La consistencia genera confianza. Elige una posición y mantenla.'},
        {name:'Anticuado profesional',emoji:'💼',summary:'Fuertes instintos de jerarquía.',desc:'La edad y la antigüedad juegan un papel importante en cómo ves las relaciones. Valoras la experiencia y esperas deferencia. Otros pueden verte como difícil de abordar.',traits:['La antigüedad determina la mayoría de las decisiones','Incómodo cuando los subordinados no están de acuerdo','El consejo está hecho para seguirse','Dificultad para dar crédito a los jóvenes'],tip:'Intenta escuchar sin dar consejos la próxima vez. Puede sorprenderte.'},
        {name:'Fósil viviente',emoji:'🗿',summary:'100% anticuado. Completamente fosilizado.',desc:'La edad y la jerarquía definen tu visión del mundo. Luchas por ver el mérito independientemente de la antigüedad.',traits:['Edad = rango, siempre','Las opiniones de los jóvenes se desestiman por defecto','Ser cuestionado se siente irrespetuoso','El cambio es inherentemente sospechoso'],tip:'Pregunta a un joven su opinión hoy — y simplemente escucha.'}
      ]
    },
    vocab:{
      title:'Test de vocabulario coreano',subtitle:'10 preguntas · 6 niveles',shareText:'¡Acabo de hacer el test de vocabulario coreano! ¿Cuál es tu nivel?',
      questions:[
        {q:'"심심한 사과" — ¿qué significa "심심하다" aquí?',a:['Aburrido / soso','Sincero / de corazón','Dulce','Delicioso']},
        {q:'"무운을 빈다" — "무운" significa:',a:['Buena suerte en batalla / fortuna militar','Formación de nubes','Movimiento de baile','Sin suerte']},
        {q:'"사필귀정" — ¿qué significa?',a:['Al final la justicia triunfa','Todo cambia','Las acciones tienen consecuencias','La historia se repite']},
        {q:'"금상첨화" — ¿qué significa?',a:['Mejor todavía / la guinda del pastel','Fuego y hielo','Belleza oculta','Matar dos pájaros de un tiro']},
        {q:'"조삼모사" — ¿qué significa?',a:['Engañado por diferencias superficiales (lo mismo, diferente presentación)','Rutina matutina','Plan astuto','Tres más cuatro']},
        {q:'"혼용무도" — ¿qué significa?',a:['Caos total / desorden','Artes marciales mixtas','Ritual antiguo','Mezcla de culturas']},
        {q:'"괄목상대" — ¿qué significa?',a:['Mejora notable','Concurso de miradas','Rivales de antaño se reencuentran','Diálogo cara a cara']},
        {q:'"아전인수" — ¿qué significa?',a:['Interpretar todo en propio beneficio','Llevar agua a tu campo','Autosuficiente','Ir con la corriente']},
        {q:'"오리무중" — ¿qué significa?',a:['Completamente a oscuras / perdido en la niebla','Viaje de cinco millas','Pato en la niebla','Sin pistas']},
        {q:'"명경지수" — ¿qué significa?',a:['Mente cristalina / espejo de agua quieta','Futuro brillante','Fase de espejo','Lago tranquilo']},
      ],
      levels:[
        {name:'Nivel 4 · Brote',emoji:'🌱',summary:'Tu viaje de vocabulario coreano acaba de comenzar.',desc:'El camino es largo, pero la curiosidad te lleva a todas partes. Prueba aprender una palabra nueva al día.',traits:['La mayoría de las palabras sino-coreanas son un misterio','Los dramas coreanos te ayudan con el contexto','Bueno en fonética, más débil en significado','Cada palabra es un nuevo descubrimiento'],tip:'Apps como Naver Dictionary hacen el aprendizaje divertido. Empieza con las 100 más comunes.'},
        {name:'Nivel 4b · Retoño',emoji:'✏️',summary:'Construyendo una base.',desc:'Conoces lo básico y empiezas a sentir los patrones. Sigue así y te sorprenderás.',traits:['Conoces las expresiones más comunes','El contexto ayuda mucho','A veces confundes palabras de sonido similar','Creciendo rápido'],tip:'Lee webtoons coreanos o titulares de noticias para una exposición natural.'},
        {name:'Nivel 5 · Intermedio',emoji:'📖',summary:'Vocabulario sólido de nivel medio.',desc:'Manejas bien el coreano cotidiano. Los términos literarios o clásicos más difíciles aún te tropiezan ocasionalmente.',traits:['Cómodo con vocabulario de oficina y académico','Las expresiones literarias necesitan trabajo','Bueno adivinando por contexto','Aprendiz constante'],tip:'Prueba leer editoriales coreanas o artículos de historia para subir de nivel.'},
        {name:'Nivel 6 · Avanzado',emoji:'📚',summary:'Vocabulario fuerte — la mayoría es legible.',desc:'Manejas textos complejos con facilidad. Los modismos clásicos y los compuestos raros son tu próxima frontera.',traits:['Lee noticias coreanas con fluidez','Ocasionalmente bloqueado por modismos clásicos','El vocabulario es un punto fuerte','Aprendiz activo'],tip:'Lee literatura clásica coreana o colecciones de 사자성어 para el toque final.'},
        {name:'Nivel 7 · Experto',emoji:'🌟',summary:'Rango de vocabulario casi nativo.',desc:'Tu coreano sino es sobresaliente. Entiendes matices, contexto histórico y uso estilístico.',traits:['Capta connotaciones sutiles','Explica orígenes de palabras fácilmente','Cómodo con registros literarios y formales','Los otros te piden definiciones'],tip:'Estudia 한문 (chino clásico) para desbloquear la última capa.'},
        {name:'Nivel 8 · Maestro',emoji:'🏆',summary:'¡Maestro del vocabulario — puntuación perfecta!',desc:'Dominio excepcional del vocabulario sino-coreano en todos los registros. Podrías enseñar este material.',traits:['Maneja todos los niveles de formalidad','Entiende las raíces del chino clásico','Usa las palabras con precisión y elegancia','El vocabulario raro le es familiar'],tip:'Comparte el conocimiento — escribe o enseña. Es la mejor manera de mantenerlo afilado.'}
      ]
    },
    burnout:{
      title:'Diagnóstico de agotamiento',subtitle:'10 preguntas · 5 niveles',shareText:'¡Acabo de comprobar mi nivel de agotamiento! ¿Cuál es el tuyo?',
      questions:[
        {q:'Cuando suena el despertador un día laboral:',a:['Me levanto bien. No es para tanto.','Se siente físicamente doloroso cada mañana.','Duro, pero me las arreglo.']},
        {q:'Después del trabajo, ¿qué sueles hacer?',a:['Mis propias cosas — hobbies, ver a gente.','Me desplomo en el sofá y no puedo moverme.','Mayormente recargo pilas solo/a.']},
        {q:'Algo que antes te emocionaba, ahora:',a:['Sigue emocionándome. No ha cambiado.','Ya no puedo sentir entusiasmo.','Menos que antes.']},
        {q:'¿Cómo duermes?',a:['Bastante bien.','Duermo pero me despierto agotado/a.','Inconsistente — algunas noches bien, otras no.']},
        {q:'Cuando alguien te pide un favor:',a:['Ayudo si puedo.','Solo pensar en ello me agota.','Depende de mi energía ese día.']},
        {q:'Los fines de semana:',a:['Descanso y me recupero bien.','Sigo cansado/a todo el fin de semana.','Algo recuperado/a, pero no del todo.']},
        {q:'¿Con qué frecuencia dices "estoy cansado/a"?',a:['Solo cuando realmente lo estoy.','Es básicamente mi muletilla.','Bastante a menudo últimamente.']},
        {q:'Pensar en la próxima semana de trabajo:',a:['Normal. Solo otra semana.','Ya me estoy desanimando.','Un poco de resistencia, pero manejable.']},
        {q:'Tu motivación para hacer cosas:',a:['Sin cambios. Sigo motivado/a.','¿Motivación? ¿Qué es eso?','Más baja que antes.']},
        {q:'Ahora mismo, ¿qué te falta más?',a:['Nada importante. Estoy bien.','Tiempo para estar solo/a y simplemente respirar.','Algo pequeño — difícil de nombrar.']}
      ],
      grades:[
        {name:'Cargado al 100%',emoji:'🟢',summary:'Energía al máximo. Lo estás haciendo genial.',desc:'Estás gestionando bien tu energía. El estrés está presente pero no abruma. Sigue así — y sigue protegiendo lo que te hace sentir bien.',traits:['Las mañanas no son terribles','Puedes recuperarte los fines de semana','La motivación se mantiene estable','Sigues disfrutando lo que solías disfrutar'],tip:'Estás en buena forma. Protégelo — descansa antes de necesitarlo.'},
        {name:'Calentando motores',emoji:'🟡',summary:'La fatiga se acumula. Procede con cuidado.',desc:'Aún funciona bien, pero la energía va un paso más lento. La diferencia entre descansar e ignorarlo ahora determina cómo te sentirás en tres meses.',traits:['Las mañanas se sienten pesadas','La concentración no es lo que era','Los fines de semana no restauran del todo','"Estoy cansado/a" se está convirtiendo en habitual'],tip:'Empieza con 30 minutos al día de tiempo sin obligaciones.'},
        {name:'Luz de advertencia encendida',emoji:'🟠',summary:'Tu mente y cuerpo envían SOS.',desc:'Cambios de humor, tareas que se sienten más pesadas de lo que deberían. Si la fuerza de voluntad te ha llevado hasta aquí, ese método se está agotando. La recuperación debe venir antes que el esfuerzo.',traits:['Te irritas fácilmente con cosas pequeñas','Perdiste la motivación para muchas cosas','Quedar con gente se siente más agotador','Cosas que disfrutabas ya no te parecen interesantes'],tip:'Habla con alguien. No tienes que resolver esto solo/a.'},
        {name:'Casi vacío',emoji:'🔴',summary:'Necesitas parar y descansar — ahora.',desc:'La energía está cerca de cero. Nada parece emocionante, el futuro se siente plano, y algunos días el pensamiento de desaparecer suena como un alivio. Esto no es un problema de fuerza de voluntad.',traits:['Las tareas básicas se sienten enormes','Las emociones se sienten apagadas','El futuro no es algo a lo que se mira con expectativa','El sueño no restaura'],tip:'Está bien parar. El mundo no se derrumbará. Por favor, habla con alguien.'},
        {name:'Completamente agotado',emoji:'⚫',summary:'La recuperación es la única prioridad ahora mismo.',desc:'El agotamiento ha ido muy profundo. Tu mente y cuerpo probablemente han superado su límite. Intentar seguir adelante solo/a no es una opción — es hora de decírselo a alguien y pedir ayuda real.',traits:['La vida diaria se siente imposible','Un sentido de inutilidad se cuela','Sin expectativas para el futuro','Las emociones se han callado'],tip:'Muéstrale este resultado a alguien cercano. No tienes que cargar esto solo/a.'}
      ]
    },
    digital:{
      title:'Test de dependencia digital',subtitle:'10 preguntas · 5 niveles',shareText:'¡Acabo de descubrir mi nivel de dependencia del móvil! ¿Cuál es el tuyo?',
      questions:[
        {q:'Lo primero que haces al despertar:',a:['Estirarme o lavarme la cara.','Coger el móvil antes de estar despierto/a.','El móvil a los pocos minutos.']},
        {q:'Durante las comidas, tu móvil:',a:['Boca abajo o en otro sitio.','En la mesa, con la pantalla visible.','Intento alejarlo pero a veces fallo.']},
        {q:'Cuando recibes una notificación:',a:['Compruebo cuando me venga bien.','Lo compruebo de inmediato — no puedo dejarlo.','Normalmente rápido, a veces espero.']},
        {q:'Sin wifi, batería baja. Te sientes:',a:['Bien — no es gran cosa.','Ansioso/a e inquieto/a.','Algo incómodo/a.']},
        {q:'Justo antes de dormir:',a:['El móvil apartado al menos 30 mins antes de dormir.','Scrolling hasta que me duermo.','El móvil en la cama pero intento no usarlo mucho.']},
        {q:'Visitas al baño:',a:['El móvil se queda fuera.','Siempre llevo el móvil.','A veces.']},
        {q:'En una conversación, alguien está hablando y tú:',a:['Atención total, móvil alejado.','Miro las notificaciones sin pensar.','Intento concentrarme pero a veces compruebo.']},
        {q:'Tiempo sin tu móvil — podrías:',a:['Disfrutarlo.','Apenas aguantar una hora.','Una hora está bien; más se vuelve incómodo.']},
        {q:'Notificaciones de tiempo de pantalla:',a:['Las compruebo e intento reducir.','Las descarto inmediatamente.','Las miro pero no cambio realmente el comportamiento.']},
        {q:'Después de un largo día:',a:['Leer, caminar o descansar sin pantallas.','Scroll en redes sociales hasta dormirme.','Mezcla de pantallas y otras cosas.']}
      ],
      grades:[
        {name:'Minimalista digital',emoji:'🌿',summary:'El móvil es una herramienta — no tu amo.',desc:'Usas dispositivos inteligentes de forma intencionada, no por hábito. Estás presente en las conversaciones y cómodo/a en el silencio. Una relación rara y saludable con la tecnología.',traits:['Cómodo/a sin teléfono durante horas','Las notificaciones no gobiernan tu atención','El tiempo de pantalla es genuinamente bajo','La vida offline se siente natural'],tip:'Tu equilibrio es envidiable. Sigue siendo un modelo para otros.'},
        {name:'Usuario equilibrado',emoji:'📲',summary:'Uso saludable, con ocasionales excesos.',desc:'Usas las herramientas digitales bien sin que te consuman. La conciencia es tu mayor activo — notas cuando te excedes.',traits:['"Un momento" a veces se convierte en una hora','No todas las notificaciones reciben respuesta','El tiempo sin móvil es manejable','Comes con el móvil a veces'],tip:'Poner el móvil boca abajo 30 minutos antes de dormir cambia la calidad del sueño.'},
        {name:'Adicción inicial',emoji:'🔔',summary:'Cogiendo el móvil sin razón.',desc:'El chequeo habitual del móvil está tomando forma. Abres apps sin propósito, te sientes inquieto/a sin la pantalla. El pensamiento "debería reducir" aparece a menudo.',traits:['Sin móvil te sientes inquieto/a','La pantalla necesita verse durante las comidas','Scrolling hasta dormirte','Las alertas de tiempo de pantalla se ignoran'],tip:'Empieza por silenciar notificaciones no esenciales. El silencio es curativo.'},
        {name:'Sin móvil no puedo',emoji:'📡',summary:'El mundo digital es más cómodo que el real.',desc:'Online se siente más fácil que offline. Estar sin el móvil es estresante. Las situaciones del mundo real se sienten extrañas.',traits:['El móvil siempre va al baño','Las notificaciones nocturnas se comprueban','Sin wifi = ansiedad','"Un momento" siempre se convierte en una hora'],tip:'Prueba una hora con el móvil en otra habitación. Se vuelve más fácil cada vez.'},
        {name:'Uno con el móvil',emoji:'🤖',summary:'Tu mano derecha ya es un smartphone.',desc:'Pantalla encendida desde que te despiertas hasta que te duermes. El mundo real es el lugar desconocido. El móvil es infraestructura esencial, no una herramienta.',traits:['La app de tiempo de pantalla está desactivada o ignorada','No puedes saber la hora sin el móvil','Sin cargador el día está arruinado','Lo miras a mitad de conversación'],tip:'Pon el móvil un minuto y mira por la ventana. Eso es el comienzo.'}
      ]
    },
    tmi:{
      title:'Test de tipo TMI',subtitle:'9 preguntas · 8 tipos',shareText:'¡Acabo de descubrir mi estilo de conversación! ¡Pruébalo tú también!',
      questions:[
        {q:'Acaba de pasar algo interesante. ¿Cuándo se lo dices a la gente?',a:['Al instante — no puedo esperar.','Cuando el momento se siente bien.']},
        {q:'Cuando compartes una historia, ¿cuántos detalles incluyes?',a:['Detalle completo — escenario, contexto, emociones, todo.','Solo los puntos clave.']},
        {q:'Cuando alguien comparte noticias contigo, tú:',a:['Respondes emocionalmente — primero la empatía.','Das tu análisis honesto.']},
        {q:'Un amigo está desahogándose sobre un problema. Tú:',a:['Escuchas y empatizas.','Escuchas y sugieres soluciones.']},
        {q:'Ambiente de conversación preferido:',a:['Animado — activo, mucho intercambio.','Tranquilo — significativo y centrado.']},
        {q:'Después de una larga conversación, sueles sentirte:',a:['Energizado/a — la conversación es combustible.','Un poco agotado/a — necesito descomprimirme.']},
        {q:'En chats de grupo, tiendes a:',a:['Impulsar la conversación.','Reaccionar y apoyar los mensajes de otros.']},
        {q:'Cuando tienes algo importante que decir, tú:',a:['Lo dices inmediatamente, luego lo refinas.','Lo piensas bien y hablas una vez.']},
        {q:'Cuando escuchas algo nuevo, instintivamente:',a:['Lo conectas con tu propia experiencia y compartes.','Lo guardas y reflexionas tranquilamente.']}
      ],
      results:{
        'live-reporter':{name:'Reportero en directo',emoji:'📡',summary:'En cuanto pasa, en detalle, con plena empatía.',desc:'Cuando algo pasa, hay que compartirlo de inmediato y con detalle — con color emocional. Nunca eres aburrido/a de compañía. Solo vigila que dejes espacio para que hable la otra persona.',traits:['Los mensajes de WhatsApp siempre tienen varios párrafos','Mensajes largos que son realmente divertidos de leer','El animador del grupo','Las reacciones son generosas y reales'],tip:'A veces, déjales hablar primero. Escuchar también es una habilidad de conversación.',match:'Editor de titulares'},
        'rapid-analyst':{name:'Analista rápido',emoji:'🧮',summary:'Rápido, detallado, lógico.',desc:'Rápido para compartir y minucioso en los detalles, pero primero la información sobre la emoción. Comunicación clara y eficiente — especialmente útil en grupos de toma de decisiones.',traits:['Las explicaciones son rápidas y precisas','Largo pero siempre tiene un punto','Lide con datos en debates','Las emociones se expresan un poco rígidamente'],tip:'Preciso no siempre es suficiente. A veces "suena duro" es lo que se necesita.',match:'Empático lento'},
        'warm-narrator':{name:'Narrador cálido',emoji:'📖',summary:'Lentamente, profundamente, con sentimiento.',desc:'Elige el momento adecuado antes de hablar, luego cuenta la historia con calidez y profundidad. Las conversaciones se profundizan contigo alrededor.',traits:['"¿Sabes qué? En realidad..." empieza conversaciones','Gran instinto para contar historias','Fuerte empatía por las emociones de los demás','Los mensajes largos que se leen hasta el final'],tip:'Las buenas historias no tienen que estar perfectamente cronometradas. Un poco antes también está bien.',match:'Analista rápido'},
        'headline-editor':{name:'Editor de titulares',emoji:'📰',summary:'Con timing, detallado, con la conclusión primero.',desc:'Espera el momento adecuado, explica completamente, pero siempre aterriza en un punto claro. Genial resumiendo situaciones grupales.',traits:['Piensa antes de hablar','Explicaciones largas, conclusiones claras','Prefiere la conversación significativa a la charla trivial','Prefiere en persona sobre los mensajes'],tip:'Las conclusiones no siempre tienen que llegar primero. Compartir el proceso también es conversación.',match:'Reportero en directo'},
        'slow-empath':{name:'Empático lento',emoji:'🫂',summary:'Con timing, breve, emocionalmente cálido.',desc:'Silencioso/a, pero cuando hablas es para cuidar los sentimientos de la otra persona. Una frase bien colocada puede cambiar toda la atmósfera.',traits:['Pocas palabras pero tienen peso','Lee los sentimientos antes de responder','Silenciosamente fundamental en las conversaciones','"Sentarse contigo en silencio es suficiente"'],tip:'Piensa en voz alta más a menudo. Tu frase significa más de lo que sabes.',match:'Analista rápido'},
        'cool-summarizer':{name:'Resumidor frío',emoji:'✂️',summary:'Con timing, breve, lógico.',desc:'Solo habla cuando es necesario, con las menos palabras posibles. Implacablemente eficiente. Brilla en entornos de trabajo donde se valora la claridad.',traits:['Los mensajes de una línea son la norma','Mínima charla trivial','Retroalimentación directa sin suavizar','No gasta energía en palabras innecesarias'],tip:'La eficiencia está bien, pero la charla sin sentido a veces construye conexión real.',match:'Narrador cálido'},
        'late-bloomer':{name:'Florecedor tardío',emoji:'🌱',summary:'Más tarde, brevemente, con calidez.',desc:'Sin prisa, pocas palabras, pero cuando llegan son cálidas. El tipo que está calladamente ahí cuando alguien necesita apoyo.',traits:['"Hablemos de ello después" es tu movimiento','Casi nunca reacciona en el momento','Las palabras sinceras llegan después de reflexión cuidadosa','Presencia silenciosa pero confiable'],tip:'El buen momento a veces pasa. Incluso los pensamientos inacabados valen la pena compartir.',match:'Reportero en directo'},
        'quiet-realist':{name:'Realista silencioso',emoji:'🧱',summary:'Más tarde, brevemente, lógicamente.',desc:'Menos palabras, timing más cuidadoso, hechos sobre sentimientos. Silencioso — pero lo que dices es lo más confiable.',traits:['Pausa de tres segundos antes de cada frase','Casi nada de expresión emocional','"¿Cuál es el punto?" es tu filtro interno','El tiempo a solas es recarga'],tip:'Tu silencio puede leerse como indiferencia. Un pequeño reconocimiento ayuda mucho.',match:'Reportero en directo'}
      }
    }
  }
};
